USE master;
GO
CREATE DATABASE TIENDA_CODIGO_FACILITO_III
ON
(
	NAME = TIENDA_DATA,
	FILENAME = 'G:\ProyectosSQL\SQL_CODIGO_FACILITO\TIENDA_DATA.mdf',
	SIZE = 20,
	MAXSIZE = 60
)
LOG ON
(	
	NAME = TIENDA_LOG,
	FILENAME = 'G:\ProyectosSQL\SQL_CODIGO_FACILITO\TIENDA_LOG.ldf',
	SIZE = 20,
	MAXSIZE = 60
);
GO