--COMENTARIO DENTRO DE SQL SERVER


/*
BIENVENIDOS AL CURSO DE SQL SERVER 
TODOS ESTAN CORDIALMENTE INVITADOS
ESTE CURSO ES TOTALMENTE GRATIS
BIENVENIDOS AL CURSO DE SQL SERVER 
TODOS ESTAN CORDIALMENTE INVITADOS
ESTE CURSO ES TOTALMENTE GRATIS
BIENVENIDOS AL CURSO DE SQL SERVER 
TODOS ESTAN CORDIALMENTE INVITADOS
ESTE CURSO ES TOTALMENTE GRATIS
BIENVENIDOS AL CURSO DE SQL SERVER 
TODOS ESTAN CORDIALMENTE INVITADOS
ESTE CURSO ES TOTALMENTE GRATIS
BIENVENIDOS AL CURSO DE SQL SERVER 
TODOS ESTAN CORDIALMENTE INVITADOS
ESTE CURSO ES TOTALMENTE GRATIS*/

--BIENVENIDOS AL CURSO DE SQL SERVER 
--TODOS ESTAN CORDIALMENTE INVITADOS
--ESTE CURSO ES TOTALMENTE GRATIS
--BIENVENIDOS AL CURSO DE SQL SERVER 



USE master;
